AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  ExampleJavaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: qmau.me.vnnlp.handler.VnNlpHandler
      CodeUri: ./target/vnnlp-1.0.0.jar
      Runtime: java8